theme = "vscode-default"

[editor]
default-yank-register = "+"
line-number = "relative"
scrolloff = 8
cursorline = true
completion-timeout = 5
completion-replace = true
bufferline = "always"
color-modes = true
text-width = 120
#rulers = [120]
insert-final-newline = false
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
end-of-line-diagnostics = "hint"
completion-trigger-len = 1

[editor.statusline]
left = [
  "mode",
  "spinner",
  "read-only-indicator",
  "file-modification-indicator",
  "version-control",
  "file-name",
]
center = []
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
  "file-indent-style",
  "file-type",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true
inlay-hints-length-limit = 50

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 0

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

# [editor.inline-diagnostics]
# cursor-line = "warning"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-ret = "open_below"
C-S-ret = "open_above"
D = "delete_char_backward"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection"]
C-ret = ["collapse_selection", "keep_primary_selection", "open_below"]
C-S-ret = ["collapse_selection", "keep_primary_selection", "open_above"]
D = "delete_char_backward"

[keys.insert]
A-h = "move_char_left"
A-j = "move_line_down"
A-k = "move_line_up"
A-l = "move_char_right"
C-ret = "open_below"
C-S-ret = "open_above"
C-space = "completion"
D = "delete_char_backward"