[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "ruff", args = [
    "format",
    "--stdin-filename",
    "file.py",
    "-",
] }
auto-format = false

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
python.analysis.diagnosticMode = "openFilesOnly"
python.analysis.autoSearchPaths = true
python.analysis.indexing = true

python.analysis.useLibraryCodeForTypes = true
python.analysis.typeCheckingMode = "off"
reportMissingImports = "error"
reportUnboundVariable = "error"
reportMissingTypeStubs = false

python.analysis.autoImportCompletions = true
python.analysis.completeFunctionParens = true

python.pythonPath = "./venv/bin/python"

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]
