[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "ruff", args = [
    "format",
    "--stdin-filename",
    "file.py",
    "-",
] }
#diagnostic-severity = "error"
auto-format = false

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
python.analysis.autoSearchPaths = true
python.analysis.useLibraryCodeForTypes = true
python.analysis.diagnosticMode = "openFilesOnly"
python.analysis.autoImportCompletions = true
python.analysis.typeCheckingMode = "basic"
python.analysis.completeFunctionParens = true
python.analysis.indexing = false
python.pythonPath = "./venv/bin/python"
reportMissingImports = "error"
reportMissingTypeStubs = false

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]
