inherits = "dark_plus"

#"ui.background" = {bg = "#000000" }
"ui.statusline" = { fg = "#ffffff", bg = "#2d2d30" }
"ui.statusline.inactive" = { bg = "#68217a" }
"ui.statusline.normal" = { bg = "#007acc" }
"ui.statusline.insert" = { bg = "#4ec9b0" }
"ui.statusline.select" = { bg = "#c586c0" }
