inherits = "dark_plus"

# "ui.background" = {bg = "background" }
"ui.background" = {bg = "#000000" }
"ui.statusline" = { bg = "widget" }
# "ui.statusline" = { bg = "background" }
"ui.statusline.inactive" = { bg = "widget" }
# "ui.statusline.inactive" = { bg = "background" }
"ui.statusline.normal" = { bg = "blue" }
"ui.statusline.insert" = { bg = "dark_green" }
"ui.statusline.select" = { bg = "magenta" }
